config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  devise_for :users

  devise_scope :user do
    get 'users/callbacks/registration_user', to: 'users/callbacks#registration_user'
    get 'users/callbacks/authorize_user', to: 'users/callbacks#authorize_user'

    root 'invent/workplaces#index'
  end

  authenticate :user, lambda { |u| u.role? :admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :users

  # Инвентаризация
  namespace :invent do
    # Отделы
    resources :workplace_counts, param: :workplace_count_id do #, except: :edit
      collection do
        # Сформировать файл со списком РМ и их составом
        get 'generate_pdf/:division', to: 'workplace_counts#generate_pdf', constraints: { division: /\d+/ }
        # post 'create_list', to: 'workplace_counts#create_list'
      end
    end
    # Рабочие места
    resources :workplaces, except: [:update], param: :workplace_id do
      collection do
        # Вывести все РМ списком
        get 'list_wp', to: 'workplaces#list_wp'
        # Подтвердить/отклонить конфигурацию РМ
        put 'confirm', to: 'workplaces#confirm'
        # Скачать скрипт для генерации файла конфигурации ПК
        get 'pc_script', to: 'workplaces#send_pc_script'
        # Получить количество замороженных рабочих мест у данного отдела
        get 'count_freeze/:workplace_count_id', to: 'workplaces#count_freeze', constraints: { workplace_count_id: /\d+/ }
      end

      put 'update', as: 'update', on: :collection
      delete 'hard_destroy', to: 'workplaces#hard_destroy', on: :member
    end

    # Скачивание файлов, прикрепленных к рабочему месту
    # прямой путь используется в /services/invent/workplaces/list_wp.rb
    get 'attachments/download/:id', to: 'attachments#download', as: 'attachments/download'

    # Запросы с ЛК
    # Проверка доступа к разделу "Вычислительная техника" в ЛК.
    get '***REMOVED***_invents/svt_access', to: '***REMOVED***_invents#svt_access'
    # Инициализация
    get '***REMOVED***_invents/init_properties', to: '***REMOVED***_invents#init_properties'
    # Получить данные по выбранном отделу (список РМ, макс. число, список работников отдела)
    get '***REMOVED***_invents/show_division_data/:division', to: '***REMOVED***_invents#show_division_data', constraints: { division: /\d+/ }
    # Получить данные о системном блоке из аудита
    get '***REMOVED***_invents/pc_config_from_audit/:invent_num',
        to: '***REMOVED***_invents#pc_config_from_audit',
        constraints: { invent_num: /.*/ }
    # Расшифровать файл конфигурации ПК, загруженный пользователем.
    post '***REMOVED***_invents/pc_config_from_user', to: '***REMOVED***_invents#pc_config_from_user'
    # Записать данные о РМ
    # post '***REMOVED***_invents/create_workplace', to: '***REMOVED***_invents#create_workplace'
    # Получить данные о РМ
    # get '***REMOVED***_invents/edit_workplace/:workplace_id', to: '***REMOVED***_invents#edit_workplace', constraints: { workplace_id: /\d+/ }
    # Обновить данные о РМ
    # patch '***REMOVED***_invents/update_workplace/:workplace_id', to: '***REMOVED***_invents#update_workplace', constraints: { workplace_id: /\d+/ }
    # Удалить РМ
    # delete '***REMOVED***_invents/destroy_workplace/:workplace_id', to: '***REMOVED***_invents#destroy_workplace', constraints: { workplace_id: /\d+/ }
    # Создать PDF файл со списком РМ для отдела
    get '***REMOVED***_invents/generate_pdf/:division', to: '***REMOVED***_invents#generate_pdf', constraints: { division: /\d+/ }
    # Скачать скрипт для генерации файла конфигурации ПК
    get '***REMOVED***_invents/pc_script', to: '***REMOVED***_invents#send_pc_script'
    # Проверить, существует ли техника с указанным инвентарным номером
    get '***REMOVED***_invents/existing_item', to: '***REMOVED***_invents#existing_item'
    # Показать данные по указанной технике
    get '***REMOVED***_invents/invent_item', to: '***REMOVED***_invents#invent_item'

    resources :items, except: [:new, :create], param: :item_id do
      collection do
        get 'avaliable/:type_id', to: 'items#avaliable', constraints: { type_id: /\d+/ }
        get 'busy', to: 'items#busy'
        # Получить данные о системном блоке из аудита
        get 'pc_config_from_audit/:invent_num', to: 'items#pc_config_from_audit', constraints: { invent_num: /.*/ }
        # Расшифровать файл конфигурации ПК, загруженный пользователем.
        post 'pc_config_from_user', to: 'items#pc_config_from_user'
        # Отправить технику на склад
        post 'to_stock', to: 'items#to_stock'
        # Списать технику
        post 'to_write_off', to: 'items#to_write_off'
        # Отметить как правильно переклеенный штрих-код
        get 'assign_invalid_barcode_as_true/:item_id', to: 'items#assign_invalid_barcode_as_true'
        # Создать прих.ордер на картридж и сразу расходный на РМ
        post 'add_cartridge', to: 'items#add_cartridge'
      end
    end

    resources :vendors, only: [:index, :create, :destroy], param: :vendor_id
    resources :models, param: :model_id
  end

  # Эталоны
  namespace :standard do

  end

  # Склад
  namespace :warehouse do
    # Получить информацию о всех расположениях
    get 'locations/load_locations', to: 'locations#load_locations'

    get 'locations/load_rooms/:building_id', to: 'locations#rooms_for_building'

    resources :items
    # Разделить одну технику на множество с разным расположением на складе
    put 'items/:id/split', to: 'items#split'
    
    resources :orders, only: [:new, :edit, :destroy] do
      get 'in', to: 'orders#index_in', on: :collection
      get 'out', to: 'orders#index_out', on: :collection
      get 'write_off', to: 'orders#index_write_off', on: :collection
      get 'archive', to: 'orders#archive', on: :collection
      get 'print', to: 'print', on: :member
      post 'create_in', to: 'orders#create_in', on: :collection
      post 'create_out', to: 'orders#create_out', on: :collection
      post 'create_write_off', to: 'orders#create_write_off', on: :collection
      post 'execute_in', to: 'orders#execute_in', on: :member
      post 'execute_out', to: 'orders#execute_out', on: :member
      post 'execute_write_off', to: 'orders#execute_write_off', on: :member
      post 'prepare_to_deliver', to: 'orders#prepare_to_deliver', on: :member
      put 'update_in', to: 'orders#update_in', on: :member
      put 'update_out', to: 'orders#update_out', on: :member
      put 'update_write_off', to: 'orders#update_write_off', on: :member
      put 'confirm', to: 'orders#confirm', on: :member
      put 'assign_op_receiver', to: 'orders#assign_operation_receiver', on: :member
    end
    # Добавление файла к исполненному расходному ордеру
    post 'attachment_orders', to: 'attachment_orders#create', as: 'attachment_orders'
    # Скачивание файла, прикрепленое к исполненному расходному ордеру
    get 'attachment_orders/download/:id', to: 'attachment_orders#download', as: 'attachment_orders/download'

    resources :supplies

    resources :requests, only: [:index, :edit, :update] do
      put 'send_for_analysis', to: 'requests#send_for_analysis', on: :member
      put 'confirm_request_and_order', to: 'requests#confirm_request_and_order', on: :member
      put 'assign_new_executor', to: 'requests#assign_new_executor', on: :member
      put 'send_to_owner', to: 'requests#send_to_owner', on: :member
      put 'save_recommendation', to: 'requests#save_recommendation', on: :member
      put 'expected_is_stock', to: 'requests#expected_is_stock', on: :member
      
      get 'close', to: 'requests#close', on: :member
    end
      put 'requests/:id/ready', to: 'requests#ready'

    get 'attachment_requests/download/:id', to: 'attachment_requests#download', as: 'attachment_requests/download'
  end

  # Получить html-код кнопки "Добавить запись"
  get 'link/new_record', to: 'application#link_to_new_record'

  resources :user_isses, only: :index do
    # Получить список пользователей указанного отдела
    get 'users_from_division/:division', to: 'user_isses#users_from_division', on: :collection
    # Получить список техники привязанной за пользователем
    get :items, to: :items
  end

  resource :statistics, only: :show
  get 'statistics/export', to: 'statistics#export', as: 'statistics/export'

  resources :signs, param: :sign_id, only: [:index] do
    collection do
      # Загрузить все признаки
      get 'load_signs', to: 'signs#load_signs'
    end
  end

  namespace :api do
    namespace :v1 do
      namespace :invent do
        resources :items, only: :index 
      end
      # Очистить кэш во всём приложении
      get 'clear_cache_app', to: 'cache#clear'
    end

    namespace :v2 do
      namespace :invent do
        resources :items, only: :index

        # Поиска техники по штрих-коду, возвращает объект
        get 'items/:barcode', to: 'items#barcode'
         # Поиска техники по filtering_params, возвращает массив
        get 'search_items', to: 'items#search_items'
      end
    end

    namespace :v3 do
      namespace :warehouse do
        # Добавление новой заявки категории 1
        post 'requests/new_office_equipment', to: 'requests#new_office_equipment'
        # Ответ от пользователя (подтверждение/отклонение обработанной заявки) из Orbita
        post 'requests/answer_from_user/:id', to: 'requests#answer_from_user'

        # Ответ от начальника (подтверждение/отклонение сформированного расходного ордера) из SSD
        post 'requests/answer_from_owner/:id', to: 'requests#answer_from_owner'
        # Получение json ссылок на скачивание файлов конкретной заявки для SSD (Приложения)
        get 'requests/request_files', to: 'requests#request_files'
        # Скачивать вложенный документ заявки в SSD "Приложения"
        get 'requests/download_attachment_request/:id', to: 'requests#download_attachment_request'
      end
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/models/invent/attachment.rb
module Invent
  class Attachment < BaseInvent
    self.primary_key = :id
    self.table_name = "#{table_name_prefix}attachments"

    belongs_to :workplace, foreign_key: 'workplace_id', inverse_of: :attachments

    mount_uploader :document, DocumentUploader
  end
end

app/models/invent/base_invent.rb
module Invent
  class BaseInvent < ApplicationRecord
    self.abstract_class = true
    self.table_name_prefix = 'invent_'
    establish_connection "#{Rails.env}_invent".to_sym

    def self.by_type_id(type_id)
      return all if type_id.to_i.zero?

      where(type_id: type_id)
    end
  end
end

app/models/invent/model.rb
module Invent
  class Model < BaseInvent
    self.primary_key = :model_id
    self.table_name = "#{table_name_prefix}model"

    default_scope { order(:item_model) }

    has_many :model_property_lists, dependent: :destroy
    has_many :items, dependent: :restrict_with_error
    has_many :warehouse_items, class_name: 'Warehouse::Item', foreign_key: 'invent_model_id', dependent: :restrict_with_error

    belongs_to :vendor, optional: false
    belongs_to :type, optional: false

    validates :type, :vendor, :item_model, presence: true, reduce: true

    scope :vendor_id, ->(vendor_id) { where(vendor_id: vendor_id) }
    scope :type_id, ->(type_id) { where(type_id: type_id) }
    scope :item_model, ->(item_model) { where('item_model LIKE ?', "%#{item_model}%") }

    accepts_nested_attributes_for :model_property_lists, reject_if: proc { |attr| attr['property_id'].to_i.zero? || attr['property_list_id'].to_i.zero? }

    def property_list_for(prop)
      model_property_lists.find_by(property: prop).try(:property_list)
    end

    def fill_item_model
      return unless vendor

      if new_record?
        self.item_model = "#{vendor.vendor_name} #{item_model}"
      elsif vendor_id_changed?
        old_vendor = Vendor.find(vendor_id_was)
        item_model.gsub!(/^#{old_vendor.vendor_name}/, vendor.vendor_name)
      end
    end
  end
end

app/models/invent/model_property_list.rb
module Invent
  class ModelPropertyList < BaseInvent
    self.primary_key = :model_property_list_id
    self.table_name = "#{table_name_prefix}model_property_list"

    belongs_to :model, optional: false
    belongs_to :property, optional: false
    belongs_to :property_list, optional: false

    validates :model, :property, :property_list, presence: true
  end
end

app/models/invent/pc_exception.rb
module Invent
  class PcException < BaseInvent
    self.table_name = "#{table_name_prefix}pc_exceptions"
  end
end

app/models/invent/property.rb
module Invent
  class Property < BaseInvent
    self.primary_key = :property_id
    self.table_name = "#{table_name_prefix}property"

    # Свойства ПК, которые должны быть заполнены из утилиты SysConfig
    FILE_DEPENDING = %w[mb ram video cpu hdd].freeze
    # Свойства, которые не обязательны для заполнения в случае, если для текущего экземпляра техники указан инвентарный
    # номер, который встречается в модели PcException.
    PROP_MANDATORY_EXCEPT = %w[network_connection mb ram video cpu hdd].freeze
    # Свойства, обозначающие дату
    DATE_PROPS = %w[date date_month].freeze
    # Свойства, обозначающие выбор из списка
    LIST_PROPS = %w[list list_plus].freeze
    # Наименование свойств, к которым может назначаться техника со склада со штрих-кодом в property_values
    LIST_TYPE_FOR_BARCODES = Invent::Property.where(assign_barcode: true).pluck(:short_description).map(&:downcase).freeze

    has_many :property_to_types, dependent: :destroy
    has_many :types, through: :property_to_types
    has_many :property_values, dependent: :destroy
    has_many :property_lists, dependent: :destroy
    has_many :model_property_lists, dependent: :restrict_with_error
    has_many :warehause_property_values, class_name: 'Warehouse::PropertyValue', foreign_key: 'property_id', dependent: :destroy
  end
end

app/models/invent/property_list.rb
module Invent
  class PropertyList < BaseInvent
    self.primary_key = :property_list_id
    self.table_name = "#{table_name_prefix}property_list"

    has_many :model_property_lists, dependent: :restrict_with_error
    has_many :property_values, dependent: :restrict_with_error

    belongs_to :property, optional: false
  end
end

app/models/invent/property_to_type.rb
module Invent
  class PropertyToType < BaseInvent
    self.primary_key = :property_to_type_id
    self.table_name = "#{table_name_prefix}property_to_type"

    belongs_to :type
    belongs_to :property
  end
end

app/controllers/api/v1/invent/items_controller.rb
module Api
  module V1
    module Invent
      class ItemsController < ApplicationController
        skip_before_action :authenticate_user!

        def index
          result = if params[:invent_num].present?
                     ::Invent::Item
                       .where(invent_num: params[:invent_num], status: :in_workplace)
                       .includes(%i[type model barcode_item workplace])
                       .as_json(
                         include: [
                           :barcode_item,
                           {
                             workplace: {
                               except: %i[create_time]
                             }
                           },
                           {
                             type: {
                               except: %i[create_time modify_time]
                             }
                           }
                         ],
                         except: %i[create_time modify_time],
                         methods: :short_item_model
                       )
                   elsif params[:tn].present?
                     user = User.find_by(tn: params[:tn])
                     employee = UsersReference.info_users("personnelNo==#{params[:tn]}")

                     if user.present? && employee.first.present? && employee.first.try(:[], 'departmentForAccounting').present? &&
                        user.workplace_responsibles.find_by(workplace_count: ::Invent::WorkplaceCount.find_by(division: employee.first.try(:[], 'departmentForAccounting'))).present?

                       items = ::Invent::Item
                                 .includes(:barcode_item, :model, :type, { workplace: %i[workplace_count] })
                                 .where(status: :in_workplace)
                                 .by_division(employee.first.try(:[], 'departmentForAccounting'))
                                 .as_json(
                                   include: [
                                     :barcode_item,
                                     {
                                       type: { except: %i[create_time modify_time] }
                                     },
                                     {
                                       workplace: {
                                         except: %i[create_time]
                                       }
                                     }
                                   ],
                                   except: %i[create_time modify_time],
                                   methods: :short_item_model
                                 )

                       employee_list = items.map { |it| it['workplace']['id_tn'] }

                       employees_wp = UsersReference.info_users("id=in=(#{employee_list.compact.join(',')})")
                       items.each do |it|
                         employee = employees_wp.find { |emp| emp['id'] == it['workplace']['id_tn'] }

                         it['fio_user_iss'] = employee.present? ? employee['fullName'] : 'Ответственный не найден'
                       end
                       items
                     else
                       []
                     end
                   else
                     []
                   end

          render json: result
        end
      end
    end
  end
end

app/views/invent/workplaces/_edit_form.slim
.well-main
  = render partial: 'workplace_header'
  .well-content
    .row
      .col-md-7.col-lg-6
        = render partial: 'common_data'
      .col-md-17.col-lg-18
        = render partial: 'item_list'

= render partial: 'manually_pc_modal'
= render partial: 'new_item'

app/views/invent/workplaces/_filters.slim
.col-sm-4.col-xlg-3.col-fhd-2.multiline-buffer
  = link_to "Добавить РМ", new_invent_workplace_path, class: "btn btn-primary btn-block btn-sm"
.col-sm-6.col-md-4.col-xlg-3.col-fhd-3.multiline-buffer
  = button_tag type: :button, class: "btn btn-default btn-block btn-sm", "ng-click": "wp_index.listType = !wp_index.listType; wp_index.setFilters()" do
    span ng-if="wp_index.listType"
      = fa_icon "toggle-on lg", class: "text-success"
    span ng-if="!wp_index.listType"
      = fa_icon "toggle-off lg", class: "text-danger"
    |  Показывать состав
.col-sm-5.col-md-4.col-xlg-3.multiline-buffer
  .input-group.input-group-sm.form-input-sm.multiline-select
    ui-select ng-model="wp_index.selectedFilters.building" on-select="wp_index.reloadWorkplaces(); wp_index.loadRooms()" theme="bootstrap"
      ui-select-match placeholder="Корпус"
        | {{ $select.selected.name }}
      ui-select-choices group-by="'site_name'" repeat="obj in wp_index.filters.buildings | filter: $select.search"
        div ng-bind-html="obj.name | highlight: $select.search"
    span.input-group-btn
      = button_tag type: :button, class: "btn-default", "ng-click": "wp_index.selectedFilters.building = ''; wp_index.selectedFilters.room = ''; wp_index.reloadWorkplaces(); wp_index.clearRooms()",
        "uib-tooltip": "Очистить", "tooltip-append-to-body": true, "ng-disabled": "!wp_index.selectedFilters.building" do
        = fa_icon "times"
.col-sm-5.col-md-4.col-xlg-3.multiline-buffer
  .input-group.input-group-sm.form-input-sm.multiline-select
    ui-select ng-model="wp_index.selectedFilters.room" on-select="wp_index.reloadWorkplaces()" theme="bootstrap"
      ui-select-match placeholder="Комната"
        | {{ $select.selected.name }}
      ui-select-choices repeat="obj in wp_index.filters.rooms | filter: $select.search"
        div ng-bind-html="obj.name | highlight: $select.search"
    span.input-group-btn
      = button_tag type: :button, class: "btn-default", "ng-click": "wp_index.selectedFilters.room = ''; wp_index.reloadWorkplaces()",
        "uib-tooltip": "Очистить", "tooltip-append-to-body": true, "ng-disabled": "!wp_index.selectedFilters.room" do
        = fa_icon "times"
.col-sm-4.col-md-4.col-xlg-3.col-fhd-2.multiline-buffer
  = text_field_tag "", "", class: "form-control input-sm", placeholder: "Инвентарный №", "ng-model-options": "{ debounce: 300 }",
    "ng-model": "wp_index.selectedFilters.invent_num", "ng-change": "wp_index.reloadWorkplaces()", "oninput": "this.value = this.value.replace(/[;]/g, '');"
.col-sm-5.col-md-4.col-xlg-3.col-fhd-2.multiline-buffer
  = text_field_tag "", "", class: "form-control input-sm", placeholder: "ID РМ", "ng-model-options": "{ debounce: 300 }",
    "ng-model": "wp_index.selectedFilters.workplace_id", "ng-change": "wp_index.reloadWorkplaces()", "oninput": "this.value = this.value.replace(/[;]/g, '');"
.col-sm-5.col-md-4.col-xlg-3.col-fhd-2.multiline-buffer
  = select_tag "", "", class: "form-control input-sm", "ng-model": "wp_index.selectedFilters.workplace_type_id",
    "ng-options": "type.workplace_type_id as type.short_description for type in wp_index.filters.types", "ng-change": "wp_index.reloadWorkplaces()"
.col-sm-5.col-md-4.col-xlg-3.col-fhd-2.multiline-buffer
  .input-group.input-group-sm.form-input-sm.multiline-select
    ui-select ng-model="wp_index.selectedFilters.division" on-select="wp_index.reloadWorkplaces()" theme="bootstrap"
      ui-select-match placeholder="Отдел"
        | {{ $select.selected.division }}
      ui-select-choices repeat="obj in wp_index.filters.divisions | filter: $select.search"
        div ng-bind-html="obj.division | highlight: $select.search"
    span.input-group-btn
      = button_tag type: :button, class: "btn-default", "ng-click": "wp_index.generatePDF()", "uib-tooltip": "Сформировать перечень для печати",
        "tooltip-append-to-body": true, "ng-disabled": "(!wp_index.selectedFilters.division && wp_index.filters.divisions.length > 1) || !wp_index.filters.divisions" do
        = fa_icon "print"
      = button_tag type: :button, class: "btn-default", "ng-click": "wp_index.selectedFilters.division = ''; wp_index.reloadWorkplaces()",
        "uib-tooltip": "Очистить", "tooltip-append-to-body": true, "ng-disabled": "!wp_index.selectedFilters.division" do
        = fa_icon "times"
.col-sm-4.col-lg-3.col-fhd-2.multiline-buffer
  = select_tag "", "", class: "form-control input-sm", "ng-model": "wp_index.selectedFilters.status",
    "ng-options": "status as translated for (status, translated) in wp_index.filters.statuses", "ng-change": "wp_index.reloadWorkplaces()"
.col-sm-5.col-md-4.col-xlg-3.multiline-buffer
  = text_field_tag "", "", class: "form-control input-sm", placeholder: "ФИО", "ng-model-options": "{ debounce: 300 }",
    "ng-model": "wp_index.selectedFilters.fullname", "ng-change": "wp_index.reloadWorkplaces()", "type": 'text', "oninput": "this.value = this.value.replace(/[;]/g, '');"
.col-sm-6.col-md-5.col-xlg-4.col-fhd-3.col-fhd-offset-21.multiline-buffer
  = button_tag type: :button, class: "btn btn-default btn-block btn-sm", "ng-click": "wp_index.showOnlyWithAttachmentFilter()" do
    span ng-if="wp_index.selectedFilters.show_only_with_attachments"
      = fa_icon "toggle-on lg", class: "text-success"
    span ng-if="!wp_index.selectedFilters.show_only_with_attachments"
      = fa_icon "toggle-off lg", class: "text-danger"
    |  Показывать с файлами

app/views/invent/workplaces/_help.slim
.row.animate-show.ng-hide ng-show="wp.workplace.workplace_type.workplace_type_id != 0"
  - if current_user.one_of_roles? :admin, :manager, :worker  
    span ng-if="wp.workplace.location_obj.room && wp.workplace.location_obj.room.security_category_id != wp.workplace.no_secrecy.id"
      .col-sm-24
        .row
          .col-sm-24
            p.bg-danger.context-info
              = "{{ wp.message_for_security_category }}"
  .col-sm-24
    u Варианты состава:
    .row
      .col-sm-24
        p.bg-info.context-info ng-bind="wp.workplace.workplace_type.full_description"

.row
  .col-sm-24
    u Описание цветовой схемы списка техники:
    .row
      .col-sm-24
        ul.list-unstyled
          li
            = fa_icon "circle", class: "text-danger"
            '  - Указанную технику пользователь должен сдать в УИВТ
          li
            = fa_icon "circle", class: "text-info"
            '  - Указанную технику пользователь должен получить в УИВТ
          li
            = fa_icon "circle"
            '  - Указанная техника находится на рабочем месте пользователя

app/views/invent/workplaces/_workplace_header.slim
.navbar.navbar-default role="navigation-content"
  .collapse.navbar-collapse.navbar-collapse-content
    div.ng-hide.animate-show ng-show="wp.workplace.workplace_id"
      .navbar-text
        | ID РМ:
        span<> ng-bind="wp.workplace.workplace_id"
      .divider-vertical
    .navbar-text
      span
        ' Отдел:

    .navbar-form.navbar-left
      .form-group
        span ng-class="{ 'bg-freeze ': wp.workplace.count_freeze && wp.workplace.count_freeze != 0 }" uib-tooltip="В текущем отделе имеются замороженные рабочие места" tooltip-enable="wp.workplace.count_freeze && wp.workplace.count_freeze != 0"
          .ui-select
            ui-select ng-model="wp.workplace.division" on-select="wp.loadUsers()" theme="bootstrap"
              ui-select-match 
                | {{ $select.selected.division }}
              ui-select-choices repeat="obj in wp.divisions | filter: $select.search"
                div ng-bind-html="obj.division | highlight: $select.search"
      span<>
      - if !current_user.role? :***REMOVED***_user
        .form-group
          = button_tag type: :button, class: "btn-default", "uib-tooltip": "Показывает, будут ли включены ограничения на состав РМ",
            "ng-click": "wp.workplace.disabled_filters = !wp.workplace.disabled_filters" do
            div ng-if="!wp.workplace.disabled_filters"
              = fa_icon "toggle-on lg", class: "text-success"
              |  Ограничения включены
            div ng-if="wp.workplace.disabled_filters"
              = fa_icon "toggle-off lg", class: "text-danger"
              |  Ограничения отключены
      span<>
      - if !current_user.role? :***REMOVED***_user
        .form-group.dropdown
          = button_tag type: :button, class: "btn btn-default", "data-toggle": "dropdown" do
            ' Файлы
            span.caret
          ul.dropdown-menu style="width: max-content;" ng-click="$event.stopPropagation()"
            li.text-center
              = label_tag :attachment do
                .btn
                  = fa_icon "folder-open"
                  '  Загрузить файл
              = file_field_tag "attachment", "document-upload": "true", class: "hidden-attachment", "multiple": true
            li class="divider" ng-if="(wp.workplace.attachments_attributes | filter:{_destroy:1}).length != wp.workplace.attachments_attributes.length"
            li ng-repeat="attachment in wp.workplace.attachments_attributes" ng-hide="attachment._destroy"
              a ng-href="" 
                span style="margin-right: 10px;" ng-bind="attachment.filename"                
                .pull-right
                  span style="margin-right: 10px;" ng-if="attachment.id && attachment.filename != 'Файл отсутствует'"
                    i class="fa fa-download" uib-tooltip="Скачать файл" class="text-primary pointer" ng-click="wp.downloadFile(attachment.id)"
                  i class="fa fa-trash-o" uib-tooltip="Удалить файл" class="text-danger pointer" ng-click="wp.deleteFile(attachment)" tooltip-append-to-body="true"

    .divider-vertical

    .navbar-form.navbar-right
      .btn-group
        = button_tag "Готово", class: "btn-success", "ng-click": "wp.saveWorkplace()"
        = link_to "Отмена", invent_workplaces_path, class: "btn btn-default"
    .divider-vertical.navbar-right
    - if !current_user.role? :***REMOVED***_user
      span.ng-hide ng-show="wp.workplace.workplace_id"
        .navbar-form.navbar-right
          = button_tag "Удалить, как дубликат", class: "btn-danger", "uib-tooltip": "Удалить РМ без создания ордеров", "ng-click": "wp.destroyWp()"
        .divider-vertical.navbar-right